name:                multi-containers
version:             0.1.0.2
github:              "zliu41/multi-containers"
license:             BSD3
author:              "Ziyang Liu <free@cofree.io>"
maintainer:          "Ziyang Liu <free@cofree.io>"
copyright:           "2019 Ziyang Liu"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
synopsis:            A few multimap variants.
category:            Data Structures

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         A library that provides a few multimap variants.

dependencies:
  - base >= 4.7 && < 5
  - containers >= 0.5.10.2 && < 0.7

library:
  source-dirs: src

tests:
  hspec:
    main: Main.hs
    source-dirs: test/hspec
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - hspec >= 2.4.8 && < 2.8
      - multi-containers
