name:                multi-containers
version:             0.1.0.0
github:              "zliu41/multi-containers"
license:             BSD3
author:              "Ziyang Liu"
maintainer:          "free@cofree.io"
copyright:           "2019 Ziyang Liu"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
synopsis:            A few variants of multimaps.
category:            Data Structures

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/zliu41/multi-containers#readme>

dependencies:
  - base >= 4.7 && < 5
  - containers >= 0.5.10.2 && < 0.7

library:
  source-dirs: src

executables:
  test-gen:
    main: Main.hs
    source-dirs: test-gen
    dependencies:
      - extra >= 1.6.9 && < 1.7
      - directory >= 1.3.0.2 && < 1.4
      - filepath >= 1.4.1.2 && < 1.5

tests:
  hspec:
    main: Main.hs
    source-dirs: test/hspec
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - hspec >= 2.4.8 && < 2.8
      - multi-containers
