name:                multi-containers
version:             0.1.0.0
github:              "zliu41/multi-containers"
license:             BSD3
author:              "Ziyang Liu"
maintainer:          "free@cofree.io"
copyright:           "2019 Ziyang Liu"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/zliu41/multi-containers#readme>

dependencies:
  - base >= 4.7 && < 5
  - containers
  - extra

library:
  source-dirs: src

executables:
  test-gen:
    main: Main.hs
    source-dirs: test-gen
    dependencies:
      - filepath

tests:
  hspec:
    main: Main.hs
    source-dirs: test/hspec
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - hspec
      - multi-containers
